import {createClient} from 'npm:@supabase/supabase-js@2';
import {interpretMessage,normalize,clarificationFor} from '../_shared/intent-parser.js';
import {naturalRequest,resolveReportPeriod,helpTopic,helpAnswer,helpPrompt,reportPeriodPrompt} from '../_shared/natural-assistant.js';
const SB=Deno.env.get('SUPABASE_URL')!,KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const db=createClient(SB,KEY,{auth:{persistSession:false,autoRefreshToken:false}});let BOT=Deno.env.get('BOT_TOKEN')??'';
async function token(){if(BOT)return BOT;const r=await db.rpc('get_planeja_telegram_bot_token');if(r.error)throw r.error;BOT=String(r.data??'');return BOT}
async function sha(s:string){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function api(method:string,body:any,dry=false,out:any[]=[]){if(dry){out.push({method,payload:body});return}const r=await fetch(`https://api.telegram.org/bot${await token()}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(`${method} ${r.status}`)}
async function forward(body:any,secret:string){const r=await fetch(`${SB}/functions/v1/telegram-router-next`,{method:'POST',headers:{'content-type':'application/json','x-telegram-bot-api-secret-token':secret},body:JSON.stringify(body)});return new Response(await r.text(),{status:r.status,headers:{'content-type':r.headers.get('content-type')??'text/plain'}})}
async function user(tid:number){return(await db.from('users').select('*').eq('telegram_user_id',tid).maybeSingle()).data}
function hasAccess(u:any){return !!u&&(u.beta_access===true||['active','trial','trialing'].includes(String(u.subscription_status||''))||(u.access_until&&new Date(u.access_until).getTime()>Date.now()))}
async function cats(uid:number){return((await db.from('categories').select('name').eq('user_id',uid)).data??[]).map((x:any)=>x.name)}
async function state(tid:number){return(await db.from('telegram_states').select('state').eq('telegram_user_id',tid).maybeSingle()).data?.state??null}
async function setState(tid:number,s:any){await db.from('telegram_states').upsert({telegram_user_id:tid,state:s,updated_at:new Date().toISOString()},{onConflict:'telegram_user_id'})}
async function clearState(tid:number){await db.from('telegram_states').delete().eq('telegram_user_id',tid)}
function money(v:any,c:string){return`${Number(v)} ${c}`}
const FIXED=['aluguel','financiamento','prestacao','mensalidade','condominio','seguro','internet','celular','telefone','assinatura','academia','escola','faculdade','netflix','spotify','streaming','emprestimo','cartao de credito','fatura'];
function likelyRecurring(t:string,c:string,d:string){const h=normalize(`${t} ${c} ${d}`);return FIXED.some(x=>h.includes(x))}
function txKb(id:number,s=false){const rows:any[]=[[{text:'🔄 Alterar transação',callback_data:`edit:${id}`}]];if(s)rows.push([{text:'🔁 Tornar recorrente',callback_data:`suggestrec:${id}:yes`},{text:'Agora não',callback_data:`suggestrec:${id}:no`}]);return{inline_keyboard:rows}}
function offsetMinutes(date:Date,tz:string){const z=new Intl.DateTimeFormat('en-US',{timeZone:tz,timeZoneName:'longOffset'}).formatToParts(date).find(p=>p.type==='timeZoneName')?.value??'GMT+00:00';const m=z.match(/GMT([+-])(\d{1,2})(?::(\d{2}))?/);if(!m)return 0;const n=Number(m[2])*60+Number(m[3]??0);return m[1]==='-'?-n:n}
function localToUtc(date:string,h:number,min:number,tz:string){const[y,m,d]=date.split('-').map(Number),wall=Date.UTC(y,m-1,d,h,min);let out=new Date(wall-offsetMinutes(new Date(wall),tz)*60000);const o2=offsetMinutes(out,tz);out=new Date(wall-o2*60000);return out.toISOString()}
function addIsoDay(date:string,n:number){const[y,m,d]=date.split('-').map(Number),x=new Date(Date.UTC(y,m-1,d));x.setUTCDate(x.getUTCDate()+n);return x.toISOString().slice(0,10)}
function brDate(date:string){const[y,m,d]=date.split('-');return`${d}/${m}/${y}`}
async function buildReport(u:any,p:any){const tz=u.timezone||'UTC',startUtc=localToUtc(p.start_date,0,0,tz),endUtc=localToUtc(addIsoDay(p.end_date,1),0,0,tz);const q=await db.from('transactions').select('kind,amount,currency,category,description,occurred_at').eq('user_id',u.id).gte('occurred_at',startUtc).lt('occurred_at',endUtc).order('occurred_at',{ascending:true});if(q.error)throw q.error;const rows=q.data??[],range=p.start_date===p.end_date?brDate(p.start_date):`${brDate(p.start_date)} a ${brDate(p.end_date)}`;if(!rows.length)return`📊 Relatório • ${p.label||range}\n${range}\n\nNão há movimentações registradas nesse período. 🍃`;const by:any={};for(const r of rows){const c=String(r.currency||'BRL'),b=by[c]??={receita:0,gasto:0,count:0,cats:{}};b[r.kind]=Number(b[r.kind]||0)+Number(r.amount||0);b.count++;if(r.kind==='gasto'){const cat=String(r.category||'outros');b.cats[cat]=Number(b.cats[cat]||0)+Number(r.amount||0)}}const lines=[`📊 Relatório • ${p.label||range}`,range];for(const [cur,b] of Object.entries<any>(by)){const saldo=b.receita-b.gasto;lines.push('',`${cur}`,`Receitas: ${money(b.receita,cur)}`,`Gastos: ${money(b.gasto,cur)}`,`Saldo: ${money(saldo,cur)}`,`Lançamentos: ${b.count}`);const cats=Object.entries<number>(b.cats).sort((a,b)=>b[1]-a[1]).slice(0,3);if(cats.length){lines.push('Maiores gastos:');for(const [cat,val] of cats)lines.push(`• ${cat}: ${money(val,cur)}`)}}return lines.join('\n')+'\n\nSe quiser, pode pedir outro período do seu jeito. 🍃'}
Deno.serve(async req=>{const out:any[]=[];try{const secret=req.headers.get('x-telegram-bot-api-secret-token')??'';if(secret!==await sha(await token()))return new Response('unauthorized',{status:401});const dry=new URL(req.url).searchParams.get('dry_run')==='1',up=await req.json(),m=up.message,cb=up.callback_query,tid=m?.from?.id??cb?.from?.id,chat=m?.chat?.id??cb?.message?.chat?.id;if(!tid||!chat)return Response.json({ok:true,ignored:true});const u=await user(tid);if(!hasAccess(u)){await api('sendMessage',{chat_id:chat,text:'🍃 Seu acesso ao Planeja Mais não está ativo. Durante o beta, use seu convite; depois do lançamento, será necessária uma assinatura ativa.'},dry,out);return Response.json({ok:true,handled:'access_required',emitted:out})}if(cb||String(m?.text??'').startsWith('/'))return await forward(up,secret);if(!u?.onboarding_completed)return await forward(up,secret);const text=String(m.text).trim(),now=new Date(),tz=u.timezone||'UTC',categories=await cats(u.id),st=await state(tid);const meta=naturalRequest(text,{now,timezone:tz});
if(meta?.kind==='tutorial_request'){await setState(tid,{type:'tutorial_v3',step:0});await api('sendMessage',{chat_id:chat,text:'🍃 Vamos fazer um novo tutorial. Durante o treinamento, nada do que você escrever será registrado nos seus dados. Vou te mostrar tudo na prática, com frases naturais.'},dry,out);await api('sendMessage',{chat_id:chat,text:'🍃 1/5 • Receitas e despesas\n\nEscreva do seu jeito uma receita ou despesa.\n\nEx.: comprei pão por 500 ienes',reply_markup:{inline_keyboard:[[{text:'Pular esta etapa',callback_data:'tut3:skip'}],[{text:'Encerrar tutorial',callback_data:'tut3:exit'}]]}},dry,out);return Response.json({ok:true,handled:'natural_tutorial_start',emitted:out})}
if(meta?.kind==='report_request'){const rp:any=meta.payload;if(rp.period==='unspecified'){await setState(tid,{type:'report_period',attempts:0});await api('sendMessage',{chat_id:chat,text:reportPeriodPrompt()},dry,out);return Response.json({ok:true,handled:'report_period_needed',emitted:out})}if(st?.type==='report_period'||st?.type==='natural_help')await clearState(tid);await api('sendMessage',{chat_id:chat,text:await buildReport(u,rp)},dry,out);return Response.json({ok:true,handled:'report',period:rp.period,emitted:out})}
if(meta?.kind==='help_request'){const topic=meta.payload?.topic;if(topic){if(st?.type==='natural_help')await clearState(tid);await api('sendMessage',{chat_id:chat,text:helpAnswer(topic)},dry,out);return Response.json({ok:true,handled:'contextual_help',topic,emitted:out})}await setState(tid,{type:'natural_help',attempts:0});await api('sendMessage',{chat_id:chat,text:helpPrompt()},dry,out);return Response.json({ok:true,handled:'help_started',emitted:out})}
if(st?.type==='report_period'){if(/^(?:cancelar|cancela|deixa|esquece|voltar)$/i.test(normalize(text))){await clearState(tid);await api('sendMessage',{chat_id:chat,text:'Tudo bem. Cancelei o pedido de relatório. 🍃'},dry,out);return Response.json({ok:true,handled:'report_cancelled',emitted:out})}const rp=resolveReportPeriod(text,{now,timezone:tz});if(rp){await clearState(tid);await api('sendMessage',{chat_id:chat,text:await buildReport(u,rp)},dry,out);return Response.json({ok:true,handled:'report_followup',period:rp.period,emitted:out})}const attempts=Number(st.attempts||0)+1;await setState(tid,{type:'report_period',attempts});await api('sendMessage',{chat_id:chat,text:attempts<2?reportPeriodPrompt():'Ainda preciso de um período para montar o relatório. Pode dizer só “hoje”, “esta semana”, “este mês”, “semana passada”, “agosto” ou uma data como “11/09”. 🍃'},dry,out);return Response.json({ok:true,handled:'report_period_retry',emitted:out})}
if(st?.type==='natural_help'){const directIntent=interpretMessage(text,{defaultCurrency:u.default_currency||'BRL',customCategories:categories,now,timezone:tz});if(directIntent.kind!=='unknown'){await clearState(tid);const p:any=directIntent.payload;if(directIntent.kind==='transaction'){const q=await db.from('transactions').insert({user_id:u.id,...p,source:'telegram'}).select('*').single();if(q.error)throw q.error;const suggest=q.data.kind==='gasto'&&likelyRecurring(text,q.data.category,q.data.description);const txDate=new Date(q.data.occurred_at).toLocaleDateString('pt-BR',{timeZone:u.timezone||'UTC'});await api('sendMessage',{chat_id:chat,text:`✅ ${q.data.kind==='receita'?'Receita':'Gasto'} registrado com sucesso:\n\nTipo: ${q.data.kind}\nValor: ${money(q.data.amount,q.data.currency)}\nCategoria: ${q.data.category}\nDescrição: ${q.data.description}\nData: ${txDate}`,reply_markup:txKb(q.data.id,suggest)},dry,out);return Response.json({ok:true,matched:'transaction_after_help',emitted:out})} }if(/^(?:cancelar|cancela|deixa|esquece|voltar|sair)$/i.test(normalize(text))){await clearState(tid);await api('sendMessage',{chat_id:chat,text:'Tudo bem. Saí do modo de ajuda. Pode continuar falando comigo normalmente. 🍃'},dry,out);return Response.json({ok:true,handled:'help_cancelled',emitted:out})}let topic=helpTopic(text);if(!topic){const guessed=interpretMessage(text,{defaultCurrency:u.default_currency||'BRL',customCategories:categories,now,timezone:tz});if(guessed.kind==='transaction')topic=guessed.payload?.kind==='receita'?'income':'expense';else if(guessed.kind==='recurring_expense')topic='recurring';else if(guessed.kind==='commitment')topic='commitment';else if(guessed.kind==='deadline_task')topic='deadline';else if(guessed.kind==='savings_goal')topic='goal'}if(topic){await clearState(tid);await api('sendMessage',{chat_id:chat,text:helpAnswer(topic)},dry,out);return Response.json({ok:true,handled:'help_followup',topic,emitted:out})}const attempts=Number(st.attempts||0)+1;await setState(tid,{type:'natural_help',attempts});await api('sendMessage',{chat_id:chat,text:attempts<2?'Entendi que você precisa de ajuda, mas ainda não ficou claro onde travou. Me conta o que você estava tentando fazer — por exemplo, lançar algo, corrigir um lançamento, organizar uma conta que se repete, um compromisso, um prazo, uma meta ou entender seu relatório. 🍃':'Ainda não consegui identificar o ponto exato. Tente me dizer o objetivo em uma frase curta, como “quero lançar um gasto antigo”, “quero corrigir uma transação” ou “quero ver meu mês”. 🍃'},dry,out);return Response.json({ok:true,handled:'help_retry',emitted:out})}
const intent=interpretMessage(text,{defaultCurrency:u.default_currency||'BRL',customCategories:categories,now,timezone:tz});const p:any=intent.payload;
if(intent.kind==='savings_goal'){const q=await db.from('savings_goals').upsert({user_id:u.id,amount:p.amount,currency:p.currency,active:true},{onConflict:'user_id,currency'}).select('id').single();if(q.error)throw q.error;await api('sendMessage',{chat_id:chat,text:`🎯 Meta mensal registrada: guardar ${money(p.amount,p.currency)}. 🍃\n\nVou usar sua renda do mês para calcular o limite seguro de gastos e te alertar ao chegar a 75% desse limite.`},dry,out);return Response.json({ok:true,matched:intent.kind,emitted:out})}
if(intent.kind==='deadline_task'){const q=await db.from('deadline_tasks').insert({user_id:u.id,title:p.title,window_start:p.window_start,window_end:p.window_end,remind_on:p.remind_on,raw_text:p.raw_text,status:'pending',source:'telegram'}).select('id').single();if(q.error)throw q.error;const detail=p.deadline_type==='relative'?`Prazo final: ${p.window_end}\n\nVou te lembrar quando faltarem 7 dias para o prazo.`:`Janela: ${p.window_start} até ${p.window_end}\n\nVou te lembrar 7 dias antes do início da janela.`;await api('sendMessage',{chat_id:chat,text:`🗓️ Tarefa com prazo registrada:\n\n${p.title}\n${detail}`,reply_markup:{inline_keyboard:[[{text:'✅ Feito',callback_data:`deadline:done:${q.data.id}`},{text:'📅 Agendar',callback_data:`deadline:schedule:${q.data.id}`}]]}},dry,out);return Response.json({ok:true,matched:intent.kind,emitted:out})}
if(intent.kind==='recurring_expense'){const q=await db.from('recurring_expenses').insert({user_id:u.id,...p,active:true,source:'telegram'}).select('*').single();if(q.error)throw q.error;if(q.data.day_of_month==null)await setState(tid,{type:'rec',id:q.data.id,field:'day'});await api('sendMessage',{chat_id:chat,text:`🔁 Despesa recorrente cadastrada:\n\nDescrição: ${q.data.description}\nValor: ${q.data.amount==null?'variável / não definido':money(q.data.amount,q.data.currency)}\nCategoria: ${q.data.category}\nFrequência: mensal${q.data.day_of_month?` — dia ${q.data.day_of_month}`:''}\nStatus: ativa${q.data.day_of_month==null?'\n\nEm que dia do mês isso costuma acontecer? Envie 1 a 31 ou “pular”. 🍃':''}`},dry,out);return Response.json({ok:true,matched:intent.kind,emitted:out})}
if(intent.kind==='transaction'){const q=await db.from('transactions').insert({user_id:u.id,...p,source:'telegram'}).select('*').single();if(q.error)throw q.error;const suggest=q.data.kind==='gasto'&&likelyRecurring(text,q.data.category,q.data.description);const txDate=new Date(q.data.occurred_at).toLocaleDateString('pt-BR',{timeZone:u.timezone||'UTC'});await api('sendMessage',{chat_id:chat,text:`✅ ${q.data.kind==='receita'?'Receita':'Gasto'} registrado com sucesso:\n\nTipo: ${q.data.kind}\nValor: ${money(q.data.amount,q.data.currency)}\nCategoria: ${q.data.category}\nDescrição: ${q.data.description}\nData: ${txDate}`,reply_markup:txKb(q.data.id,suggest)},dry,out);return Response.json({ok:true,matched:intent.kind,emitted:out})}
if(intent.kind==='commitment'){const starts=localToUtc(p.local_date,p.hour,p.minute,u.timezone||'Asia/Tokyo');const q=await db.from('commitments').insert({user_id:u.id,title:p.title,starts_at:starts,raw_text:p.raw_text,source:'telegram'}).select('*').single();if(q.error)throw q.error;const when=new Date(starts).toLocaleString('pt-BR',{timeZone:u.timezone||'Asia/Tokyo',dateStyle:'short',timeStyle:'short'});await api('sendMessage',{chat_id:chat,text:`📅 Compromisso registrado com sucesso:\n\nCompromisso: ${q.data.title}\nQuando: ${when}\n\nGuardei aqui com você. 🍃`},dry,out);return Response.json({ok:true,matched:intent.kind,emitted:out})}
const clarification=clarificationFor(text);if(clarification){await api('sendMessage',{chat_id:chat,text:clarification.text},dry,out);return Response.json({ok:true,handled:'clarification',reason:clarification.reason,emitted:out})}if(st&&st.type&&!['natural_help','report_period'].includes(String(st.type)))return await forward(up,secret);await setState(tid,{type:'natural_help',attempts:0});await api('sendMessage',{chat_id:chat,text:'Quero acertar o que você quis fazer antes de mexer nos seus dados. 🍃\n\nMe conta o objetivo dessa mensagem: era algo que entrou ou saiu, um compromisso/data, um prazo, uma meta, um relatório, ou você queria ajuda com alguma função? Pode responder do seu jeito.'},dry,out);return Response.json({ok:true,handled:'safe_disambiguation',emitted:out})}catch(e){console.error(e);return Response.json({error:e instanceof Error?e.message:String(e),emitted:out},{status:500})}});